import type { Metadata } from "next";
import '@mantine/core/styles.css';
import "./globals.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { StandardNavBar } from "@/components/StandardNavBar";
import React from "react";
import ContextWrapper from "./ContextWrapper";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <head>
        <ColorSchemeScript defaultColorScheme="light" />
      </head>
      <body className={"m-0"}>
        <MantineProvider>
          <div className="flex flex-col h-screen overflow-hidden">
            <div className="flex overflow-hidden">
              <StandardNavBar />
              <main className="max-h-full flex-1 overflow-y-auto">
                <ContextWrapper>
                  {children}
                </ContextWrapper>
              </main>
            </div>
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
